
# SEO settings
title: "Fragile"
title2: "Code" # default: ""
description: "Rough sketch of my dev history"
keywords: "software, code, source, develop, frontend, backend, server, machine learning, iot"
url: http://djkooks.github.io/ # site url
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
disqus_shortname: "djKooks"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Dennis Jung"
  job      : "Software Engineer"
  bio      : "Every code is fragile. Do not believe your source. All good critic is welcome."
  thumb    : /images/author.jpg
  email    : inylove82@gmail.com
  url      : http://djkooks.github.io
  github   : http://github.com/djKooks

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
