name: Kode Kook
description: My dev-log. Hope to be better than ever.
meta_description: "My dev-log. Hope to be better than ever"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 5
domain_name: 'http://djkooks.github.io/'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]
baseurl: /

# Details for the RSS feed generator
url:            'blog url'
author:         'Dennis Jung'
